title:              BrandPark의 지식 나눔
email:              alsrhs0530@gmail.com
description:        Spring, Java를 사용하며 알게 된 기술을 익히고 공유합니다.
author:             ParkMinGon
baseurl:            # #
url:                "https://BrandPark.github.io"

# Social Profiles
twitter_username:   
github_username:    BrandPark
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
