title:              자바마니또의 Tech
email:              alsrhs0530@gmail.com
description:        Spring, Java를 사용하며 해결했던 기술을 익히고 공유합니다.
author:             자바마니또
baseurl:            # #
url:                "https://brandpark.github.io"
category_dir: category/
tag_dir: tag/

# Social Profiles
twitter_username:   
github_username:    BrandPark
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown

kramdown:
        input: GFM
        syntax_highlighter: rouge
        
        syntax highlighter_opts:
            css_class: 'highlight'
            span:
                line_numbers: false
            block:
                line_numbers: true
                start_line: 1
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
